### ISSUE TITLE
Java IO Exception (Mark Invalid) when reading in HOCON configuration over 4096 chars.

### ISSUE THREAD

**Issue by TheCahyag** [SpongePowered/Configurate#82] opened 2017-09-12 02:18 UTC
I'm using Configurate-core 3.2 to aid in persisting data (developing a Sponge plugin). 

The following statement is a call to the SpongeAPI (may not be too important)
`DataFormats.HOCON.read(someString);` 
When [this](https://pastebin.com/GneGk7U4) string is given to the reader which is ~4700 characters I get a [Mark invalid error](https://pastebin.com/v0gfSN5Z). I ran the same statement, but with a string that is ~1800 characters and did not get the mark invalid error. Which is what leads me to believe that it has to do with being over 4096 characters long (the value of READAHEAD_LEN in CommentHandlers.extractComment())

Not sure if this is a me problem, a Sponge problem or a configurate problem, just looking to get some help ^.^

Other possibility important data:
SpongeAPI: 6.1.0
SpongeVanilla: 1.11.2-6.1.0-BETA-17
Configurate-HOCON: 3.2

**Comment by ryantheleach** [comment] 2017-12-18 00:16
@TheCahyag I noticed you closed this, is this because it was fixed? If not, please leave it open.

**Comment by TheCahyag** [comment] 2017-12-18 00:33
@ryantheleach Please excuse my bad Github etiquette, I should have followed up before considering closing the issue.

I was able to "fix" this by avoiding the section of code that created the Mark Invalid error. This was done by creating a custom HoconConfigurationLoader:
``` java
HoconConfigurationLoader loader = HoconConfigurationLoader.builder()
                .setHeaderMode(HeaderMode.PRESET)
                .setSource(() -> new BufferedReader(new StringReader(hoconString)))
                .build();
```
By setting the header mode to`HeaderMode.PRESET` I was able to avoid a block of code in AbstractConfigurationLoader#load(ConfigurationOptions) that seemed to lead to the Mark Invalid exception. By avoiding that everything works as intended. 

Since I don't know if this is a bug in the code or if it was improper usage on my part I will leave it open for @zml2008 or whoever to decide. 
If there are any other questions or details I can provide I will be happy to do so in the future.

**Comment by ryantheleach** [comment] 2017-12-18 01:47
According to https://stackoverflow.com/questions/24327835/exception-at-the-bufferedreader-reset-method and searching, it appears there are 2 places in configurate where mark and reset is used.

https://github.com/zml2008/configurate/blob/aeda9b5fc49b88034533f2d3d41569eca0cf8035/configurate-core/src/main/java/ninja/leaping/configurate/loader/CommentHandlers.java - LIMIT 4096

and 

https://github.com/zml2008/configurate/blob/0b6b95818a2cf19a6d46d46c09ec7d637a17b7b9/configurate-gson/src/main/java/ninja/leaping/configurate/gson/GsonConfigurationLoader.java#L92

- Limit 1

I suspect the cause is that it just never gives up reading, only erroring once it's actually reset.

we still need to reset the location so I'm not sure what the solution is, maybe we can somehow limit how far ahead it scans.

**Comment by zml2008** [comment] 2017-12-20 20:17
Yeah, this is an issue with reading in headers that I haven't been able to resolve yet -- it only happens on files where the first line is longer than 4096 characters, which is happening here. The workaround so far has been to disable header reading for those files -- I don't want to suppress the issue silently since that could result in data loss. Any contributions would be appreciated.

**Comment by codeHusky** [comment] 2018-01-06 00:10
Ran into this while working on HuskyConfigurator.
I don't really see the benefit of "header reading", really, but why not try limiting the length of these header lines to something reasonable (perhaps 2048?)

**Closed** 2020-05-08 06:29 UTC
