### ISSUE TITLE
Cannot manually deserialize empty list

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Configurate#97] opened 2018-06-19 02:13 UTC
I have the following code to serialize my (ConfigSerializable) objects to strings:
```java
            GsonConfigurationLoader loader = GsonConfigurationLoader.builder().build();
            ConfigurationNode node = loader.createEmptyNode(ConfigurationOptions.defaults()).setValue(obj.token, obj);
            StringWriter writer = new StringWriter();
            loader.saveInternal(node, writer);
            return writer.toString();
```
and this to deserialize them:
```java
            GsonConfigurationLoader loader = GsonConfigurationLoader.builder().setSource(() -> new BufferedReader(new StringReader(string))).build();
            ConfigurationNode node = loader.load();
            return node.getValue(token);
```

This code works fine when I'm serializing objects that have lists with more than one objects inside, but fails for empty lists, where the value is represented by `"list": []`. When the list is empty, instead just populating the field with an empty list, it's leaving the object as null (fed by a NullConfigValue node). Is that supposed to happen?

**Comment by randombyte-developer** [comment] 2018-06-19 20:04
Probably duplicate of #93

**Closed** 2019-12-30 10:43 UTC
