### ISSUE TITLE
Call to disable alphabetical order.

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Configurate#31] opened 2015-05-06 00:10 UTC
If I want my config to look like this:
version="0.3"
node1 = "banana"
aForApple="yes"
I can't because nodes are locked in alphabetical order. If I could disable that, I could get that outcome.

**Comment by ryantheleach** [comment] 2015-05-06 00:11
It won't just be a problem for dev's admins get quite possessive over the layout and order of their plugin configs.

**Comment by MikaalSky** [comment] 2015-05-06 00:12
@ryantheleach Yeah. When I ran a server I liked it when things were sorted by category.

**Comment by RobertHerhold** [comment] 2015-05-06 01:39
@zml Do you think some sort of priority system would be advisable? That way when the configuration is written out, it can be ordered starting on lowest priority, and going up from there. Any un-prioritized nodes could just be written at the end, after all the others

**Comment by boformer** [comment] 2015-05-06 10:11
I reported this few months ago:
https://github.com/zml2008/configurate/issues/18

Can this be fixed by creating a fork of the typesafe hocon library?

**Comment by zml2008** [comment] 2015-05-06 13:52
possibly? but I don't really have the time to maintain that.

**Comment by Favorlock** [comment] 2015-05-11 21:38
Just noticed this issue myself. Hopefully it can be resolved soon.

**Comment by zml2008** [comment] 2015-05-12 13:48
This is an issue with the hocon library itself, and new versions of the hocon library require jdk8 so this is not something simple to fix at all.

**Comment by Favorlock** [comment] 2015-05-14 01:31
Is the issue already resolved in newer versions of the hocon library or is it just a matter of being to test it to find out?

**Comment by zml2008** [comment] 2015-05-14 03:00
It doesn't look like the map implementation used by the Hocon library has changed. However, newer library versions allow us to pass whatever map implementation we want. Unfortunately, we can't use the newer library version until we don't have users who require jdk6 (Sponge).

**Comment by ryantheleach** [comment] 2015-05-14 14:21
me:
    Is there a way to disable alphanumeric sorting of keys? I find it's useful that configs have a set order that makes it easier for the user to read and edit.

    havocp 10 hours ago  
    the Configdata structure doesn't preserve order, keys are just in random hash table order before we sort them.
    the natural follow up is why doesn't it preserve order; there's some discussion on closed github issues but in short it doesn't work well with merging (withFallback).
    if you want to load/edit/save a file, see the new ConfigDocument API in 1.3.0

**Comment by zml2008** [comment] 2015-06-29 06:08
gonna leave this as a wontfix. That will change once configurate is on jdk8 though.

**Comment by TheE** [comment] 2015-09-11 21:53
Since Sponge is now JDK8, is there a chance to reopen and fix the problem?

**Comment by zml2008** [comment] 2015-09-11 21:54
Possibly, I'll take a look at it.

**Comment by varrix** [comment] 2015-09-26 08:18
Should this perhaps be kept open until it has been decided on whether or not the JDK8 migration can potentially solve the issue?

**Comment by ryantheleach** [comment] 2016-01-10 09:34
Any chance that using the `ConfigDocument API in 1.3.0` could fix the issue with reading the config?

**Comment by CrazyFlasher** [comment] 2016-03-04 11:20
Are there any HOCON parsers that keep values order?

**Comment by codeHusky** [comment] 2017-06-11 07:36
Is this ever going to be came back to or not?

**Comment by Jamezrin** [comment] 2017-09-10 22:49
Will this be fixed at some point? This is a pain in the ass

**Comment by ryantheleach** [comment] 2017-09-11 02:09
@zml2008 Hasn't had a ton of time lately, @codeHusky @Jamezrin Are you volunteering to potentially add support for the new ConfigDocument API? That seems the only sane method considering Typesafe's current stance.

**Comment by codeHusky** [comment] 2017-09-12 16:12
I know nothing about this codebase.

**Comment by Crypnotic** [comment] 2019-01-23 22:11
Any updates on this issue. Not preserving order is very frustrating

**Comment by zml2008** [comment] 2019-01-23 23:06
this has pretty much always been a hocon issue, do they support maintaining order yet?
________________________________

**Comment by Crypnotic** [comment] 2019-01-23 23:10
I'm not too familiar with how configurate interacts with the hocon library, but according to the latest comment on: https://github.com/lightbend/config/issues/365
There is a way to accomplish ordered reading by only using the library to parse the config

**Comment by ryantheleach** [comment] 2019-02-03 10:13
To be fair, it's a hacked fork. could break at any stage, if you attempt to keep it updated. Which may be fine for SpongeForge/SpongeCommon but I think most people would rather not have those hacks in Configurate. I suspect there's an alternate way, by getting Configurate to use the dedicated document editing API's for modifying values, but that could be quite difficult to implement potentially.

**Comment by zml2008** [comment] 2020-04-12 03:52
Since at the moment it looks like we've done everything we can do on the Configurate side, any further change would have to happen on the underlying library. It also looks like our use case is not a priority for the Hocon developers, so the issue is unlikely to be fixed in the near future. 

I'll close this issue since it's unlikely we'll make progress on it as things currently stand, but I do hope that changes in the future.

**Closed by zml2008** 2020-04-12 03:52 UTC
