### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by system-operator** [SpongePowered/configurate#129] opened 2018-12-30 06:20 UTC
I spent some time last night looking, but quickly skipped over it. There appears to be no way to make 2 plugins use the same folder?

It appears to use the Mod ID as the folder name, but for the life of me I can't figure out how to make 2 separate plugins (both mine) use a single plugin directory for config. 

Oversight?

**Comment by dualspiral** [comment] 2018-12-30 12:33
This is actually a Sponge thing, nothing to do with Configurate - and it's not a bug or oversight either. I'm gonna close this as this is not a bug.

To point you in the right direction, note that `@DefaultConfig` just provides you with a _default_ file. You can ask Configurate to use a file anywhere on your file system where you have access. [What you're probably looking to do is something like this](https://gist.github.com/dualspiral/d8629b762dfd8ac16732f6246f9cd52e) - it's from memory so may need a tweak or two.

More info on configuring plugins can be seen on our docs: https://docs.spongepowered.org/stable/en/plugin/configuration/index.html

If you need any further support for this, please ask on our [forums](https://forums.spongepowered.org/), [Discord](https://discord.gg/sponge) or IRC. Thanks!

**Closed by dualspiral** 2018-12-30 12:33 UTC

**Comment by system-operator** [comment] 2018-12-30 14:43
Thank you, I realize there are methods that to achieve what I want, and you were right to close this, sorry for my haste and thank you!
